version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: blog-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www/
  nginx:
    image: nginx:1.19-alpine
    container_name: my-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: my-mysql
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
